 fi
      - name: Commit
        if: success() 
        run: |
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git add .
          git commit -m "更新日常数据" -a
  
      - name: Push changes
        if: ${{ steps.python_scripts.outputs.code_generated == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: master
          force: true
