name: TikTok日报

on:
  schedule:
    - cron: '10 12 * * *'  # 每天的20:10执行
  # push:
  #   branches:
  #     - master

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    env:
      WECHAT_UID: ${{ vars.WECHAT_UID }}
      TIKTOK_ACCOUNTS: ${{ vars.TIKTOK_ACCOUNTS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: 安装依赖环境
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行python脚本
        id: python_scripts
        run: |
          if [ -z "${{ vars.WECHAT_UID }}" ] || [ -z "${{ vars.TIKTOK_ACCOUNTS }}" ]; then
            echo "没有配置WxPusher或者TikTok账号列表，不执行脚本"
            echo "::set-output name=code_generated::false"
          else
            python src/main_tiktok.py
            echo "::set-output name=code_generated::true"
          fi
      
      - name: commit
        if: ${{ steps.python_scripts.outputs.code_generated == 'true' }}
        run: |
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git add .
          git commit -m "更新日常数据" -a

      - name: Push changes
        if: ${{ steps.python_scripts.outputs.code_generated == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: master
          force: true
